### ISSUE TITLE
`panic: runtime error: invalid memory address or nil pointer dereference` at start after staling position

### ISSUE THREAD

**Issue by ekbfh** [liftbridge-io/liftbridge#298]
I have cluster of three lb-node and three nats, many streams and random leaders of each streams.
min repl.count is 2
Sometimes i have panic trace in logs:

```
12:42:35 node-wrk liftbridge[5796]: panic: runtime error: invalid memory address or nil pointer dereference
[lb_issue_panic.txt](https://github.com/liftbridge-io/liftbridge/files/5701973/lb_issue_panic.txt)

12:42:35 node-wrk liftbridge[5796]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xc685c2]
12:42:35 node-wrk liftbridge[5796]: goroutine 273 [running]:
12:42:35 node-wrk liftbridge[5796]: github.com/liftbridge-io/liftbridge/server.(*cursorManager).getLatestCursorOffset(0xc0003f4f00, 0x102a680, 0xc0006764c0, 0xc000504260, 0x1a, 0x20, 0x0, 0x0, 0x0, 0x0)
12:42:35 node-wrk liftbridge[5796]: /home/circleci/project/server/cursors.go:207 +0x2d2
12:42:35 node-wrk liftbridge[5796]: github.com/liftbridge-io/liftbridge/server.(*cursorManager).GetCursor(0xc0003f4f00, 0x102a740, 0xc000282ab0, 0xc0001364d0, 0xc, 0xc0001364e0, 0xa, 0xe, 0xc0003b4100, 0x0)
12:42:35 node-wrk liftbridge[5796]: /home/circleci/project/server/cursors.go:148 +0x208
12:42:35 node-wrk liftbridge[5796]: github.com/liftbridge-io/liftbridge/server.(*apiServer).FetchCursor(0xc00028a028, 0x102a740, 0xc000282ab0, 0xc00024e410, 0xc00028a028, 0xc000282ab0, 0xc0002eaba0)
12:42:35 node-wrk liftbridge[5796]: /home/circleci/project/server/api.go:405 +0x1cf
12:42:35 node-wrk liftbridge[5796]: github.com/liftbridge-io/liftbridge-api/go._API_FetchCursor_Handler(0xea4e20, 0xc00028a028, 0x102a740, 0xc000282ab0, 0xc0003eecc0, 0x0, 0x102a740, 0xc000282ab0, 0xc0005041c0, 0x1c)
12:42:35 node-wrk liftbridge[5796]: /go/pkg/mod/github.com/liftbridge-io/liftbridge-api@v1.1.1-0.20201003172511-d603f70cc6a1/go/api.pb.go:3323 +0x217
12:42:35 node-wrk systemd[1]: liftbridge.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```
I believe it happens when stale node(reboot for ex) is trying to follow up a leader.

I add a log with debug when it happens. It was strange exit at 55 then systemd restarted it and panic at 95

[lb_issue_panic.txt](https://github.com/liftbridge-io/liftbridge/files/5701992/lb_issue_panic.txt)

Also please edit a issue name if i am wrong.

**Comment by tylertreat** [comment]
I believe this is same issue as https://github.com/liftbridge-io/liftbridge/issues/283, which has been addressed in master and will be included in the next release happening shortly.

**Comment by ekbfh** [comment]
Maybe the trace in issue is fixed in master, but when i was doing some test with `almost-master` build (#297) i get another cyclic error in cluster:
```
18:24:11 sevent02 liftbridge[2223]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc84e25]
18:24:11 sevent02 systemd[1]: liftbridge.service: main process exited, code=exited, status=2/INVALIDARGUMENT
18:24:11 sevent02 systemd[1]: Unit liftbridge.service entered failed state.
18:24:11 sevent02 systemd[1]: liftbridge.service failed.
18:24:53 sevent02 systemd[1]: liftbridge.service holdoff time over, scheduling restart.
18:24:53 sevent02 systemd[1]: Stopped Liftbridge service.
18:24:53 sevent02 systemd[1]: Started Liftbridge service.
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Liftbridge Version:        v1.3.0"
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Server ID:                 sevent02"
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Namespace:                 liftbridge-default"
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Default Retention Policy:  [Age: 1 day, Compact: false]"
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Default Partition Pausing: disabled"
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=info msg="Starting server on 10.0.1.84:9292..."
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:277, offset:313250}, Previous: {epoch:13048, offset:3129
18:24:53 sevent02 liftbridge[2299]: time="2020-12-16 18:24:53" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:1630, offset:60255}, Previous: {epoch:13018, offset:6024
18:24:56 sevent02 liftbridge[2299]: time="2020-12-16 18:24:56" level=error msg="Failed to fetch last offset for leader epoch for partition [subject=events.BRNL, stream=events.BRNL, partition=1]: nats: timeout"
18:24:59 sevent02 liftbridge[2299]: time="2020-12-16 18:24:59" level=error msg="Error sending replication request for partition [subject=events.BRNL, stream=events.BRNL, partition=1]: nats: timeout"
18:24:59 sevent02 liftbridge[2299]: time="2020-12-16 18:24:59" level=error msg="Failed to fetch last offset for leader epoch for partition [subject=events.BRNL, stream=events.BRNL, partition=3]: nats: timeout"
18:24:59 sevent02 liftbridge[2299]: time="2020-12-16 18:24:59" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:6477, offset:42344}, Previous: {epoch:13220, offset:4231
18:24:59 sevent02 liftbridge[2299]: time="2020-12-16 18:24:59" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:6488, offset:19582}, Previous: {epoch:13218, offset:1957
18:25:02 sevent02 liftbridge[2299]: time="2020-12-16 18:25:02" level=error msg="Error sending replication request for partition [subject=events.BRNL, stream=events.BRNL, partition=1]: nats: timeout"
18:25:02 sevent02 liftbridge[2299]: time="2020-12-16 18:25:02" level=error msg="Error sending replication request for partition [subject=events.BRNL, stream=events.BRNL, partition=3]: nats: timeout"
18:25:02 sevent02 liftbridge[2299]: time="2020-12-16 18:25:02" level=error msg="Failed to fetch last offset for leader epoch for partition [subject=events.OMSK, stream=events.OMSK, partition=0]: nats: timeout"
18:25:02 sevent02 liftbridge[2299]: time="2020-12-16 18:25:02" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:6474, offset:7668}, Previous: {epoch:13196, offset:7665}
18:25:02 sevent02 liftbridge[2299]: time="2020-12-16 18:25:02" level=warning msg="Received log leader epoch assignment for an epoch < latest epoch. This implies messages have arrived out of order. New: {epoch:6490, offset:12741}, Previous: {epoch:13070, offset:1274
18:25:05 sevent02 liftbridge[2299]: time="2020-12-16 18:25:05" level=error msg="Error sending replication request for partition [subject=events.BRNL, stream=events.BRNL, partition=1]: nats: timeout"
18:25:05 sevent02 liftbridge[2299]: time="2020-12-16 18:25:05" level=error msg="Error sending replication request for partition [subject=events.BRNL, stream=events.BRNL, partition=3]: nats: timeout"
18:25:05 sevent02 liftbridge[2299]: time="2020-12-16 18:25:05" level=error msg="Error sending replication request for partition [subject=events.OMSK, stream=events.OMSK, partition=0]: nats: timeout"
18:25:05 sevent02 liftbridge[2299]: time="2020-12-16 18:25:05" level=error msg="Failed to fetch last offset for leader epoch for partition [subject=dispose.ZBKL, stream=dispose.ZBKL, partition=1]: nats: timeout"
18:25:08 sevent02 liftbridge[2299]: time="2020-12-16 18:25:08" level=error msg="Replica sevent01 for partition [subject=events.KMRV, stream=events.KMRV, partition=0] exceeded max lag time (last seen: 15.000476937s, last caught up: 15.000476937s), removing from ISR"
18:25:08 sevent02 liftbridge[2299]: panic: runtime error: invalid memory address or nil pointer dereference
18:25:08 sevent02 liftbridge[2299]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc84e25]
18:25:08 sevent02 systemd[1]: liftbridge.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```
I fixed this only by deleting data dir in a whole liftbridge cluster.
Is this another type of panic? Unfortunately, i didn't get full trace due to downtime minimization.

**Comment by tylertreat** [comment]
Hard to say what the issue is without the stacktrace. v1.4.0 has been released, so perhaps try with this version. https://github.com/liftbridge-io/liftbridge/releases/tag/v1.4.0

**Comment by ekbfh** [comment]
I upgraded to 1.4.0 few days ago and don't saw any traces more.
close this issue
