### ISSUE TITLE
liftbridge can crash when invalid non-string parameters are passed to either subject or name of create_stream

### ISSUE THREAD

**Issue by gc-ss** [liftbridge-io/liftbridge#340]
when invalid non-string parameters are passed to either subject or name of create_stream, liftbridge (docker image liftbridge/standalone-dev) crashes with error log:

```
liftbridge-docker | time="2021-04-30 00:41:17" level=error msg="Server failed becoming leader for partition [subject=subject, stream=<function function_name at 0x7ff19cc2d3a0>, partition=0]: failed to subscribe to replication inbox: nats: invalid subject"
liftbridge-docker | panic: failed to add stream to metadata store: failed to subscribe to replication inbox: nats: invalid subject
liftbridge-docker | 
liftbridge-docker | goroutine 13 [running]:
liftbridge-docker | github.com/liftbridge-io/liftbridge/server.(*Server).Apply(0xc00034c000, 0xc0000ae2f0, 0x0, 0x0)
liftbridge-docker |     /go/pkg/mod/github.com/liftbridge-io/liftbridge@v1.3.1-0.20201125164102-383469b58204/server/fsm.go:111 +0x3e3
liftbridge-docker | github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0003088f0)
liftbridge-docker |     /go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:90 +0x2c1
liftbridge-docker | github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00025c200, 0x1, 0x40)
liftbridge-docker |     /go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:113 +0x75
liftbridge-docker | github.com/hashicorp/raft.(*Raft).runFSM(0xc000448000)
liftbridge-docker |     /go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:219 +0x42f
liftbridge-docker | github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000448000, 0xc0000feb90)
liftbridge-docker |     /go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:146 +0x55
liftbridge-docker | created by github.com/hashicorp/raft.(*raftState).goFunc
liftbridge-docker |     /go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:144 +0x66
liftbridge-docker | ./script_runner.sh: fg: line 14: job %1 not created under job control
```

**Comment by tylertreat** [comment]
Thanks, server should be performing validation to avoid panics.

**Comment by gc-ss** [comment]
Thank you very much Tyler. Much appreciated!
